### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by matheo** [Yumitoya8569/ng-conditional-validator#1]
Hi @Yumitoya8569 
Interesting stuff you have here!

I'm working on a new approach for Angular Dynamic Forms, and I'd like to integrate some ideas from your library to support the validation there; can we talk about this please?
check this article about `@myndpm/dyn-forms` and let's build some cool stuff yeah?
https://dev.to/matheo/a-new-approach-to-have-dynamic-forms-in-angular-5d11

**Comment by Yumitoya8569** [comment]
Hi @matheo 
It looks great!

I would be happy to discuss about it.

**Comment by matheo** [comment]
Nice!
do I ask too much if I ask you to present yourself [here](https://github.com/myndpm/open-source/discussions/1#discussioncomment-588244)?

I opened [this wide-open thread](https://github.com/myndpm/open-source/discussions/2) for Validators
because in the "dynamic" context, we need a robust way to describe most of the possibilities (if not all)

Later today I will gather there the stuff I've seen in other libraries so we can have a starting point :)
