### ISSUE TITLE
Is this package supporting Angular 13

### ISSUE THREAD

**Issue by ajithkumarpalani1** [Yumitoya8569/ng-conditional-validator#3]
Hi, 

I am using angular 13 in my app, Can I use ng-conditional-validator(which is supporting Angular 11 only) in my app or any other alternative available. Kindly help me. Thanks in advance

**Comment by Yumitoya8569** [comment]
@Ajithintellect 

Sorry, I publish the wrong file, now I fix it
And test it on angular 9 ~ angular 13, all work fine.
Please reinstall it:
```
npm uninstall ng-conditional-validator
npm cache clean -f
npm install ng-conditional-validator
```

If you are looking for other ways, you can refer to:
https://netbasal.com/three-ways-to-dynamically-alter-your-form-validation-in-angular-e5fd15f1e946

Or use template driven forms.

**Comment by Yumitoya8569** [comment]
@Ajithintellect 

Let me know if you clear your problem, thanks!

**Comment by ajithkumarpalani1** [comment]
@Yumitoya8569 I have checked. Now I can use this package without any issue. Thanks for support
